### ISSUE TITLE
Install info for linux?

### ISSUE THREAD

**Issue by brokenpip3** [rad-coon/oc-guy#3]
Hi, i want to try and maybe create aur package of your software but you don't provide an installation guide or step.

Prerequisite?

thanks

**Comment by FrontSchaaf** [comment]
Hey, thanks for your feedback!

I will provide more detailed instructions  at the readme.md  (maybe along with a prebuilt linux binary) this week.

To sum it up:
As it provides a qmake file instead of a cmake (cmake will follow soon) file you need Qt(5) to build it. > http://doc.qt.io/qt-5/linux.html

Further more, some shared libraries from the Qt framwork ar needed (you can find the standard deplyment instructions here: http://doc.qt.io/qt-5/linux-deployment.html#linking-the-application-to-qt-as-a-shared-library)

Without testing it, i guess you need these four libraries:
- libQt5Core.so.5
- libQt5Gui.so.5
- libQt5Widgets.so.5
- platforms\libqxcb.so


Cheers and thanx for your interest

**Comment by brokenpip3** [comment]
Thanks for your info.
So i started to write a pkgbuild file to create archlinux aur package:

1) all the four libraries are in qt5-base package (FYI)
2) i have this build error:

```
In file included from guy.h:7,
                 from main.cpp:1:
forwarding.h:6:10: fatal error: LogMainWindow.h: No such file or directory
 #include "LogMainWindow.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:624: main.o] Error 1
 
```
i think it is a simple casesensitive problem: i see logmainwindow.h, not LogMainWindow.h.
